from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


class ResearchReportService:
    """Create a deterministic, review-first Markdown report for formal runs."""

    _REPORT_FILE_NAME = "research_report.md"

    def build(
        self,
        *,
        output_dir: Path,
        run_token: str,
        run_manifest: dict[str, Any],
        outputs: list[dict[str, Any]],
    ) -> dict[str, Any]:
        output_dir = output_dir.resolve()
        report_path = output_dir / self._REPORT_FILE_NAME
        if report_path.exists():
            raise ValueError("研究报告已存在，拒绝覆盖既有运行产物。")
        content = self._render(run_manifest, outputs)
        report_path.write_text(content, encoding="utf-8")
        return {
            "kind": "research_report",
            "file_name": report_path.name,
            "uri": f"research://runs/{run_token}/{report_path.name}",
            "sha256": self._sha256(report_path),
            "size": report_path.stat().st_size,
            "metadata": {
                "format": "markdown",
                "deterministic": True,
                "scientific_conclusion": "researcher_review_required",
                "raw_data_included": False,
            },
        }

    @classmethod
    def _render(cls, run_manifest: dict[str, Any], outputs: list[dict[str, Any]]) -> str:
        experiment = run_manifest.get("experiment") or {}
        formula = run_manifest.get("formula_spec") or {}
        snapshot = run_manifest.get("data_snapshot") or {}
        protocol = run_manifest.get("project_protocol") or {}
        validation = run_manifest.get("validation") or {}
        report_context = {
            "experiment": experiment,
            "formula_spec": formula,
            "data_snapshot": snapshot,
            "project_protocol": cls._protocol_reference(protocol),
            "validation": validation,
        }
        question = cls._find_research_question(protocol, experiment)
        output_rows = [
            {
                "kind": item.get("kind"),
                "file_name": item.get("file_name"),
                "sha256": item.get("sha256"),
            }
            for item in outputs
            if item.get("kind") not in {"run_manifest", "research_evidence_package", "research_report"}
        ]
        lines = [
            "# Formal Research Run Report",
            "",
            "> This is a deterministic evidence summary generated by the local platform. "
            "It is not an automatic scientific conclusion or a claim of method superiority.",
            "",
            "## 1. Research question",
            "",
            question,
            "",
            "## 2. Frozen execution context",
            "",
            "```json",
            json.dumps(report_context, ensure_ascii=False, sort_keys=True, indent=2, default=str),
            "```",
            "",
            "## 3. Validation summary",
            "",
        ]
        if validation:
            lines.extend(
                [
                    "The run manifest contains the following validation evidence. Metrics must be interpreted "
                    "only within the registered spatial/temporal split and sampling design:",
                    "",
                    "```json",
                    json.dumps(validation, ensure_ascii=False, sort_keys=True, indent=2, default=str),
                    "```",
                ]
            )
        else:
            lines.append("No validation result was attached to this run; do not report an accuracy claim.")
        lines.extend(
            [
                "",
                "## 4. Generated visual and numeric evidence",
                "",
                "```json",
                json.dumps(output_rows, ensure_ascii=False, sort_keys=True, indent=2, default=str),
                "```",
                "",
                "## 5. Limitations and conclusion boundary",
                "",
                "- This report records one frozen execution and does not establish causal validity, generalization, or superiority.",
                "- A positive metric difference must be checked against the declared independent test, sampling design, uncertainty assumptions, and relevant literature.",
                "- Researchers must explicitly report improvement, no meaningful difference, degradation, missing evidence, and unresolved limitations; selecting only the best scene is not acceptable.",
                "- Re-run consistency is a file/numeric reproducibility check, not an independent scientific validation.",
                "",
                "## 6. Required researcher review",
                "",
                "Before publication or teaching use, an authorized researcher must review the frozen protocol, data permissions, formula evidence, validation design, figures, metrics, limitations, and the conclusion wording.",
                "",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def _find_research_question(protocol: Any, experiment: Any) -> str:
        if isinstance(protocol, dict):
            value = protocol.get("research_question")
            if isinstance(value, str) and value.strip():
                return value.strip()
        if isinstance(experiment, dict):
            value = experiment.get("name")
            if isinstance(value, str) and value.strip():
                return f"未登记独立研究问题；运行名称：{value.strip()}"
        return "未登记研究问题；不得据此形成正式科学结论。"

    @staticmethod
    def _protocol_reference(protocol: Any) -> dict[str, Any]:
        if not isinstance(protocol, dict):
            return {}
        return {
            "revision_id": protocol.get("revision_id"),
            "sha256": protocol.get("sha256"),
            "research_question": protocol.get("research_question"),
        }

    @staticmethod
    def _sha256(path: Path) -> str:
        digest = hashlib.sha256()
        with path.open("rb") as source:
            for chunk in iter(lambda: source.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()
